name: Deploy to dev

on:
  push:
    branches: ['dev']
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: etecsa-1
    
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    
    - name: Create env
      run: |
        echo "NEXT_PUBLIC_API_URL=${{ vars.NEXT_APP_API_URL_DEV }}" >> .env.production
        echo "NEXTAUTH_SECRET=${{ vars.NEXTAUTH_SECRET_DEV }}" >> .env.production
        echo "NEXTAUTH_URL=${{ vars.NEXTAUTH_URL_DEV }}" >> .env.production
        echo "NEXT_PUBLIC_SESSION_COOKIE_NAME=${{ vars.NEXT_PUBLIC_SESSION_COOKIE_NAME_DEV }}" >> .env.production
    
    - name: Stop docker compose
      run: docker compose down || true
    
    - name: Start docker compose
      run: docker compose up -d --build